export const users = {
   LOADING_USER:'LOADING_USER',
   LOGIN_USER: 'LOGIN_USER',
   LIST_USER: 'LIST_USER',
   LIST_LOADING_USER: 'LIST_LOADING_USER',
   CREATE_USER: 'CREATE_USER',
   REGISTER_USER: 'REGISTER_USER',
   UPDATE_USER: 'UPDATE_USER',
   DELETE_USER: 'DELETE_USER',
   CHANGE_STATUS_USER: 'CHANGE_STATUS_USER',
   UPDATE_PROFILE_USER: 'UPDATE_PROFILE_USER'
}

export const notes = {
   LIST_NOTE: 'LIST_NOTE',
   ADD_NOTE: 'ADD_NOTE',
   UPDATE_NOTE: 'UPDATE_NOTE',
   DELETE_NOTE: 'DELETE_NOTE'
}

export const countries = {
   LOADING_COUNTRY: 'LOADING_COUNTRY',
   LIST_COUNTRY: 'LIST_COUNTRY',
   LIST_LOADING_COUNTRY: 'LIST_LOADING_COUNTRY',
   LIST_ALL_COUNTRY: 'LIST_ALL_COUNTRY',
   LIST_ALL_LOADING_COUNTRY: 'LIST_ALL_LOADING_COUNTRY',
   CREATE_COUNTRY: 'CREATE_COUNTRY',
   UPDATE_COUNTRY: 'UPDATE_COUNTRY',
   DELETE_COUNTRY: 'DELETE_COUNTRY',
   CHANGE_STATUS_COUNTRY: 'CHANGE_STATUS_COUNTRY'
}

export const states = {
   LOADING_STATE: 'LOADING_STATE',
   LIST_STATE: 'LIST_STATE',
   LIST_LOADING_STATE: 'LIST_LOADING_STATE',
   FILTER_BY_COUNTRY_STATE: 'FILTER_BY_COUNTRY_STATE',
   FILTER_BY_COUNTRY_LOADING_STATE: 'FILTER_BY_COUNTRY_LOADING_STATE',
   CREATE_STATE: 'CREATE_STATE',
   UPDATE_STATE: 'UPDATE_STATE',
   DELETE_STATE: 'DELETE_STATE',
   CHANGE_STATUS_STATE: 'CHANGE_STATUS_STATE'
}

export const cities = {
   LOADING_CITY: 'LOADING_CITY',
   LIST_CITY: 'LIST_CITY',
   LIST_LOADING_CITY: 'LIST_LOADING_CITY',
   FILTER_BY_STATE_CITY: 'FILTER_BY_STATE_CITY',
   FILTER_BY_STATE_LOADING_CITY: 'FILTER_BY_STATE_LOADING_CITY',
   CREATE_CITY: 'CREATE_CITY',
   UPDATE_CITY: 'UPDATE_CITY',
   DELETE_CITY: 'DELETE_CITY',
   CHANGE_STATUS_CITY: 'CHANGE_STATUS_CITY'
}

export const menus = {
   LOADING_MENU: 'LOADING_MENU',
   LIST_MENU: 'LIST_MENU',
   LIST_LOADING_MENU: 'LIST_LOADING_MENU',
   LIST_ALL_MENU: 'LIST_ALL_MENU',
   LIST_ALL_LOADING_MENU: 'LIST_ALL_LOADING_MENU',
   CREATE_MENU: 'CREATE_MENU',
   UPDATE_MENU: 'UPDATE_MENU',
   DELETE_MENU: 'DELETE_MENU',
   CHANGE_STATUS_MENU: 'CHANGE_STATUS_MENU'
}

export const roles = {
   LOADING_ROLE: 'LOADING_ROLE',
   LIST_ROLE: 'LIST_ROLE',
   LIST_LOADING_ROLE: 'LIST_LOADING_ROLE',
   LIST_ALL_ROLE: 'LIST_ALL_ROLE',
   LIST_ALL_LOADING_ROLE: 'LIST_ALL_LOADING_ROLE',
   CREATE_ROLE: 'CREATE_ROLE',
   UPDATE_ROLE: 'UPDATE_ROLE',
   DELETE_ROLE: 'DELETE_ROLE',
   CHANGE_STATUS_ROLE: 'CHANGE_STATUS_ROLE'
}