export const users = {
   LOADING_USER:'LOADING_USER',
   LOGIN_USER: 'LOGIN_USER',
   LIST_USER: 'LIST_USER',
   LIST_LOADING_USER: 'LIST_LOADING_USER',
   CREATE_USER: 'CREATE_USER',
   REGISTER_USER: 'REGISTER_USER',
   UPDATE_USER: 'UPDATE_USER',
   DELETE_USER: 'DELETE_USER'
}

export const notes = {
   LIST_NOTE: 'LIST_NOTE',
   ADD_NOTE: 'ADD_NOTE',
   UPDATE_NOTE: 'UPDATE_NOTE',
   DELETE_NOTE: 'DELETE_NOTE'
}

export const countries = {
   LOADING_COUNTRY: 'LOADING_COUNTRY',
   LIST_COUNTRY: 'LIST_COUNTRY',
   LIST_LOADING_COUNTRY: 'LIST_LOADING_COUNTRY',
   CREATE_COUNTRY: 'CREATE_COUNTRY',
   UPDATE_COUNTRY: 'UPDATE_COUNTRY',
   DELETE_COUNTRY: 'DELETE_COUNTRY'
}

export const states = {
   LOADING_STATE: 'LOADING_STATE',
   LIST_STATE: 'LIST_STATE',
   LIST_LOADING_STATE: 'LIST_LOADING_STATE',
   FILTER_STATE: 'FILTER_STATE',
   FILTER_LOADING_STATE: 'FILTER_LOADING_STATE',
   CREATE_STATE: 'CREATE_STATE',
   UPDATE_STATE: 'UPDATE_STATE',
   DELETE_STATE: 'DELETE_STATE',
}

export const cities = {
   LOADING_CITY: 'LOADING_CITY',
   LIST_CITY: 'LIST_CITY',
   LIST_LOADING_CITY: 'LIST_LOADING_CITY',
   FILTER_CITY: 'FILTER_CITY',
   FILTER_LOADING_CITY: 'FILTER_LOADING_CITY',
   CREATE_CITY: 'CREATE_CITY',
   UPDATE_CITY: 'UPDATE_CITY',
   DELETE_CITY: 'DELETE_CITY'
}